# Generated by Django 2.2 on 2021-03-18 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fit_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='my_workout',
            new_name='favorite',
        ),
    ]
