# Generated by Django 2.2 on 2021-03-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit_app', '0002_auto_20210318_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite',
        ),
        migrations.AddField(
            model_name='user',
            name='my_workout',
            field=models.ManyToManyField(default=None, related_name='my_workout', to='fit_app.Workout'),
        ),
    ]
